config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base

	validates :price, numericality: true
	validates :quantity, numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all	
	end

	def create
		@product = Product.new(name: params[:name], quantity: params[:quantity], price: params[:price])
		
		if @product.save
			flash[:success] = "Product Added Successfully!"
			redirect_to @product			
		else
			@products = Product.all
			render 'index'
		end

	end

	def edit
		@product = Product.find(params[:id])
	end

	def show
		@products = Product.all	
	end

	def update
		@product = Product.find(params[:id])
		@product.name = params[:product][:name]
		@product.quantity = params[:product][:quantity]
		@product.price = params[:product][:price]
		
		if @product.save
			flash[:success] = "Product Update Success!"
			redirect_to @product
		else
			render 'edit'
		end
	end

	def destroy
		Product.find(params[:id]).destroy
		flash[:success] = "Product Delete Success!"

		redirect_to products_url
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head profile="http://www.w3.org/2005/10/profile">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<% provide(:title, "Products Home Page") %>

<nav class="navbar navbar-fixed-top header">
    <div class="col-md-12">
        <div class="navbar-header">
          
          <a href="<%= products_path %>" class="navbar-brand">Products Dashboard</a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse1">
          <i class="glyphicon glyphicon-search"></i>
          </button>
      
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse1">
          <ul class="nav navbar-nav navbar-right">
              <li><a href="<%= products_path %>" target="">Relaod Page</a></li>
           </ul>
        </div>  
     </div> 
</nav>



<!--main--> 
<div class="container" id="main">

  <div class="row">

        <% if !@product.nil? && @product.errors.any? %>
          <div class="col-lg-12 alert-danger">
          <p></p>
          <p></p>
          The form contains <%= pluralize(@product.errors.count, "error") %>
          <ul>
            <% @product.errors.full_messages.each do |message| %>
              <li><%= "#{message}" %></li>
            <% end %>           
          </ul>
          </div>
      <% end %>

  <div class="col-lg-12" style="padding-bottom: 10px;">
  		<p>Edit Product and Submit to save</p>

      <%= form_for(@product) do |form| %>

        <div class="col-lg-2">
        <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="col-lg-2">
        <%= form.text_field :quantity, class: 'form-control' %>
        </div>
        <div class="col-lg-2">
        <%= form.text_field :price, class: 'form-control' %>
        </div>
        <div class="col-lg-2">
        <%= form.submit "Save Changes", class: 'btn btn-primary' %>
        </div>

      <% end %>

    </div>

  </div>

  </div>
  <!-- /.row -->

 </div>

app/views/products/index.html.erb
<% provide(:title, "Products Home Page") %>

<nav class="navbar navbar-fixed-top header">
    <div class="col-md-12">
        <div class="navbar-header">
          
          <a href="<%= products_path %>" class="navbar-brand">Products Dashboard</a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse1">
          <i class="glyphicon glyphicon-search"></i>
          </button>
      
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse1">
          <ul class="nav navbar-nav navbar-right">
              <li><a href="<%= products_path %>" target="">Relaod Page</a></li>
           </ul>
        </div>  
     </div> 
</nav>



<!--main--> 
<div class="container" id="main">

  <div class="row">

  <%= render 'shared/error_messages' %>

  <div class="col-lg-12" style="padding-bottom: 10px;">
  		<p>Enter the details below in order to add a new product</p>

      <div class="col-lg-2">
      <%= form_tag(products_path,{ method: "post", role: "form"}) do %>
      </div>
      <div class="col-lg-2">
      <%= text_field_tag(:name,'', placeholder: "Product Name", class: "form-control", required: "") %>
      </div>
      <div class="col-lg-2">
        <%= text_field_tag(:quantity, '', placeholder: "Quantity", class: "form-control", required: "") %>
      </div>
      <div class="col-lg-2">
        <%= text_field_tag(:price, '', placeholder: "Price", class: "form-control", required: "") %>
      </div>
      <div class="col-lg-2">
        <%= submit_tag("Submit", class: "btn btn-primary") %>
      </div>

      <% end %>

  </div>

    <div class="col-lg-12">
       
       <table class="table table-hover table-bordered table-striped productsTable">
         
         <thead>
           <tr>
             <th>Name</th><th>Quantity</th><th>Price</th><th>Total Value</th><th>Date Added</th><th>Edit</th><th>Remove</th>
           </tr>
         </thead>

            <!-- loop throug the $productsArray printing details to table -->

            <% if @products.count != 0 %>

            <% totalValue = 0 %>
                    
            	<tbody>

	                <% @products.each do |product| %>

                  <% totalValue += (Float(product.quantity) * Float(product.price)) %>

	                    <tr>
	                    <td><%= product.name %></td><td><span class="pull-right"><%= number_with_delimiter(product.quantity) %></span></td><td><span class="pull-right"><%= number_to_currency(product.price) %></span></td>

	                     <td><span class="pull-right"><%= number_to_currency(Float(product.quantity) * Float(product.price)) %></span> </td>
                       <td><span class="pull-right"><%= distance_of_time_in_words(Time.now, product.created_at) %> ago</span></td>
                       <td><a href='<%= edit_product_path(product.id) %>'><i class='fa fa-edit'></i></a></td><td><%= link_to "delete", product, method: :delete, data: { confirm: "Confirm to Delete Product" } %></td>
	                   </tr>

	                <% end %>

	            </tbody>

	    		<tfoot>
		           <tr>
		             <th></th><th></th><th></th><th><span class="pull-right"><%= number_to_currency(totalValue) %></span></th><th></th><th></th><th></th>
		           </tr>
		        </tfoot> 

            <% else %>
            	<tfoot>
		           <tr>
		             <th></th><th></th><th></th><th><span class="pull-right"><%= number_to_currency(totalValue) %></span> </th><th></th><th></th><th></th>
		           </tr>
		        </tfoot> 

            	</table>
            	<span class="noProducts" ><p class='alert alert-danger'>No Products have been added yet...</p></span>

        	<% end %>



        </table>        

    </div>

  </div>
  <!-- /.row -->

 </div>

app/views/products/show.html.erb
<% provide(:title, "Products Home Page") %>

<nav class="navbar navbar-fixed-top header">
    <div class="col-md-12">
        <div class="navbar-header">
          
          <a href="<%= products_path %>" class="navbar-brand">Products Dashboard</a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse1">
          <i class="glyphicon glyphicon-search"></i>
          </button>
      
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse1">
          <ul class="nav navbar-nav navbar-right">
              <li><a href="<%= products_path %>" target="">Relaod Page</a></li>
           </ul>
        </div>  
     </div> 
</nav>



<!--main--> 
<div class="container" id="main">

  <div class="row">

  <%= render 'shared/error_messages' %>

  <div class="col-lg-12" style="padding-bottom: 10px;">
  		<p>Enter the details below in order to add a new product</p>

      <div class="col-lg-2">
      <%= form_tag(products_path,{ method: "post", role: "form"}) do %>
      </div>
      <div class="col-lg-2">
      <%= text_field_tag(:name,'', placeholder: "Product Name", class: "form-control") %>
      </div>
      <div class="col-lg-2">
        <%= text_field_tag(:quantity, '', placeholder: "Quantity", class: "form-control") %>
      </div>
      <div class="col-lg-2">
        <%= text_field_tag(:price, '', placeholder: "Price", class: "form-control") %>
      </div>
      <div class="col-lg-2">
        <%= submit_tag("Submit", class: "btn btn-primary") %>
      </div>

      <% end %>

  </div>

    <div class="col-lg-12">
       
       <table class="table table-hover table-bordered table-striped productsTable">
         
         <thead>
           <tr>
             <th>Name</th><th>Quantity</th><th>Price</th><th>Total Value</th><th>Date Added</th><th>Edit</th><th>Remove</th>
           </tr>
         </thead>

            <!-- loop throug the $productsArray printing details to table -->

            <% totalValue = 0 %>

            <% if @products.count != 0 %>
                    
            	<tbody>

	                <% @products.each do |product| %>

                    <% totalValue += (Float(product.quantity) * Float(product.price)) %>

	                    <tr>
	                    <td><%= product.name %></td><td><span class="pull-right"><%= number_with_delimiter(product.quantity) %></span></td><td><span class="pull-right"><%= number_to_currency(product.price) %></span></td>

	                     <td><span class="pull-right"><%= number_to_currency(Float(product.quantity) * Float(product.price)) %></span></td>
                       <td><span class="pull-right"><%= distance_of_time_in_words(Time.now, product.created_at) %> ago</span></td>
                       <td><a href='<%= edit_product_path(product.id) %>'><i class='fa fa-edit'></i></a></td><td><a href='<%= products_path(product.id) %>'><i class='fa fa-trash'></i></a></td>
	                   </tr>

	                <% end %>

	            </tbody>

	    		<tfoot>
		           <tr>
		             <th></th><th></th><th></th><th><span class="pull-right"><%= number_to_currency(totalValue) %></span></th><th></th><th></th><th></th>
		           </tr>
		        </tfoot> 

            <% else %>
            	<tfoot>
		           <tr>
		             <th></th><th></th><th></th><th></th><th><span class="totalValue"><%= number_to_currency(totalValue) %></span> </th><th></th><th></th>
		           </tr>
		        </tfoot> 

            	</table>
            	<span class="noProducts" ><p class='alert alert-danger'>No Products have been added yet...</p></span>

        	<% end %>



        </table>        

    </div>

  </div>
  <!-- /.row -->

 </div>

app/views/shared/_error_messages.html.erb
        <% if !@product.nil? && @product.errors.any? %>
          <div class="col-lg-12 alert-danger">
          <p></p>
          <p></p>
          The form contains <%= pluralize(@product.errors.count, "error") %>
          <ul>
            <% @product.errors.full_messages.each do |message| %>
              <li><%= "#{message}" %></li>
            <% end %>           
          </ul>
          </div>
      <% end %>

      <div class="">
        <% flash.each do |message_type, message_body| %>
          <span class="col-lg-12 alert alert-<%= message_type %>"><%= message_body %></span>
        <% end %>
      </div>